MODEL:
  TYPE: cnn
  NUM_CLASSES: 1000
  LAYERS: 6
RESNET:
  TRANS_FUN: convbasic_transform
RGRAPH:
  GROUP_NUM: 64
  DIM_FIRST: 64
  DIM_LIST: [64,128,256]
  STEM_MODE: default
BN:
  ZERO_INIT_FINAL_GAMMA: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.025
  LR_POLICY: cos
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 32
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
TEST:
  DATASET: imagenet
  SPLIT: val
  BATCH_SIZE: 25
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
