MODEL:
  TYPE: efficientnet
  NUM_CLASSES: 1000
EFFICIENT_NET:
  STEM_W: 32
  DEPTHS: [1, 2, 2, 3, 3, 4, 1]
  WIDTHS: [16, 24, 40, 80, 112, 192, 320]
  EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
  SE_RATIO: 0.25
  STRIDES: [1, 2, 2, 2, 1, 2, 1]
  KERNELS: [3, 3, 5, 3, 5, 5, 3]
  HEAD_TYPE: conv_head
  HEAD_W: 1280
  DC_RATIO: 0.0
  DC_IMP: pt
  DROPOUT_RATIO: 0.0
RGRAPH:
  DIM_LIST: [16, 24, 40, 80, 112, 192, 320]
BN:
  EPS: 0.00001
  MOM: 0.1
OPTIM:
  BASE_LR: 0.4
  LR_POLICY: cos
  STEP_SIZE: 1
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.00005
TRAIN:
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 64
  CHECKPOINT_PERIOD: 10
  EVAL_PERIOD: 1
TEST:
  DATASET: imagenet
  SPLIT: val
  BATCH_SIZE: 50
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .